demo/example widget preview feature
netizenorg/netnet.studio pull request #175
Opened 2023-03-09 19:52 UTC by Cthomp7

- Added preview function for example dialogue
- Fixed standard JS styling (some additional semicolons elsewhere & extra return)

2023-03-17 18:22 UTC, nbriz requested changes
hey @Cthomp7 this is great, one tiny suggestion (see below) after that this is ready to merge

2023-03-17 18:22 UTC, nbriz commented on www/widgets/DemoExampleMaker.js
> +  }
i'd also add a conditional here to see if there are any "line numbers" specified to highlight, if so we should highlight those using `NNE.spotlight([numbers])` if not we should reset to no spotlight `NNE.spotlight(null)` 

in netnet the global `NNE` variable represents the main instance of the [netitor](https://github.com/netizenorg/netitor) ( "spotlight" is one of it's methods, u can check out all the [other methods in the netitor docs here](https://github.com/netizenorg/netitor#methods)).

2023-03-25 23:48 UTC, nbriz commented on www/widgets/DemoExampleMaker.js
> +
looks great! just missing the `else` on line `221`
```js
else NNE.spotlight(null)
```

2023-03-26 02:02 UTC, Cthomp7 commented
Added the `else` statement on line `221`

2023-03-26 17:05 UTC, nbriz commented
looks great! merging now

2023-03-26 17:05 UTC, merged