Issue #237: dashed syntax for line number highlights
netizenorg/netnet.studio pull request #248
Opened 2024-01-12 20:46 UTC by Cthomp7

Added extra `if` statement so when `_getData` is generated it will accept dashed values (ex: `5-8`). Everything worked when downloading JSON & generating link + running example #237

2024-01-31 00:13 UTC, nbriz requested changes
i've tested with the share link && it works great! (still need to test json file, but i assume that works well too), only time it **doesn't work is when u click "preview"**, dashes get interpreted the same as commas.

side note: i'd never heard of [flatMap](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap) before! very efficient way to implement this :)

2024-01-31 00:13 UTC, nbriz commented on www/widgets/demo-example-maker/index.js
> +            console.log(Array.from({ length: end - start + 1 }, (_, i) => start + i))
don't forget to remove console.logs after everything'ss been tested

2024-02-12 18:11 UTC, nbriz commented
@Cthomp7 any progress on this one? TL;DR

- dashed lines don't work when clicking "preview" button
- need to remove console logs

2024-02-19 05:03 UTC, Cthomp7 commented
@nbriz Did and done! I cleaned up the two `console.log`s and added the same `flatMap` functionality to the preview function as well. Let me know if you have any other issues 🐸

2024-02-19 22:57 UTC, nbriz commented
perfect! thnx @Cthomp7 merging now!

2024-02-19 22:57 UTC, merged